export const CONSUMPTION_PATTERNS = [
  {
    id: "ice_factory",
    name: "مصنع ثلج",
    description: "Ice Factory",
    devices: [
      { id: "1", name: "ماكينة صنع الثلج (Ice Maker)", power_watts: 5000, quantity: 2, hours_per_day: 24 },
      { id: "2", name: "غرفة تبريد (Cold Room)", power_watts: 3000, quantity: 1, hours_per_day: 24 },
      { id: "3", name: "إضاءة (Lighting)", power_watts: 40, quantity: 10, hours_per_day: 12 },
      { id: "4", name: "مضخة مياه (Water Pump)", power_watts: 1500, quantity: 1, hours_per_day: 6 },
    ],
  },
  {
    id: "company",
    name: "شركة",
    description: "Company / Office",
    devices: [
      { id: "1", name: "مكيف هواء (Air Conditioner)", power_watts: 1500, quantity: 4, hours_per_day: 8 },
      { id: "2", name: "كمبيوتر (Computer)", power_watts: 200, quantity: 10, hours_per_day: 8 },
      { id: "3", name: "إضاءة (Lighting)", power_watts: 30, quantity: 20, hours_per_day: 8 },
      { id: "4", name: "طابعة/آلة تصوير (Printer/Copier)", power_watts: 600, quantity: 2, hours_per_day: 4 },
      { id: "5", name: "ثلاجة صغيرة (Mini Fridge)", power_watts: 150, quantity: 1, hours_per_day: 24 },
    ],
  },
  {
    id: "farm",
    name: "مزرعة",
    description: "Farm",
    devices: [
      { id: "1", name: "مضخة غاطسة (Submersible Pump)", power_watts: 3000, quantity: 1, hours_per_day: 8 },
      { id: "2", name: "إضاءة خارجية (Outdoor Lighting)", power_watts: 50, quantity: 10, hours_per_day: 12 },
      { id: "3", name: "سكن عمال (Workers Housing - General)", power_watts: 1000, quantity: 1, hours_per_day: 10 },
    ],
  },
  {
    id: "poultry_farm",
    name: "مزرعة دواجن",
    description: "Poultry Farm",
    devices: [
      { id: "1", name: "مراوح تهوية (Ventilation Fans)", power_watts: 500, quantity: 6, hours_per_day: 24 },
      { id: "2", name: "إضاءة (Lighting)", power_watts: 20, quantity: 50, hours_per_day: 16 },
      { id: "3", name: "نظام تدفئة (Heating System)", power_watts: 2000, quantity: 2, hours_per_day: 12 },
      { id: "4", name: "مضخة مياه (Water Pump)", power_watts: 750, quantity: 1, hours_per_day: 4 },
    ],
  },
  {
    id: "greenhouses",
    name: "بيوت محمية",
    description: "Greenhouses",
    devices: [
      { id: "1", name: "مراوح سحب (Exhaust Fans)", power_watts: 400, quantity: 4, hours_per_day: 10 },
      { id: "2", name: "مضخة ري (Irrigation Pump)", power_watts: 1000, quantity: 1, hours_per_day: 4 },
      { id: "3", name: "إضاءة (Lighting)", power_watts: 40, quantity: 20, hours_per_day: 6 },
    ],
  },
  {
    id: "factory",
    name: "مصنع",
    description: "General Factory",
    devices: [
      { id: "1", name: "محركات كهربائية (Electric Motors)", power_watts: 5000, quantity: 3, hours_per_day: 12 },
      { id: "2", name: "إضاءة صناعية (Industrial Lighting)", power_watts: 100, quantity: 20, hours_per_day: 12 },
      { id: "3", name: "معدات إنتاج (Production Equipment)", power_watts: 10000, quantity: 1, hours_per_day: 12 },
      { id: "4", name: "مكيفات مكاتب (Office ACs)", power_watts: 1500, quantity: 3, hours_per_day: 8 },
    ],
  },
  {
    id: "clinic",
    name: "مستوصف",
    description: "Clinic",
    devices: [
      { id: "1", name: "مكيفات (Air Conditioners)", power_watts: 1500, quantity: 5, hours_per_day: 12 },
      { id: "2", name: "إضاءة (Lighting)", power_watts: 30, quantity: 30, hours_per_day: 12 },
      { id: "3", name: "ثلاجة أدوية (Medicine Refrigerator)", power_watts: 300, quantity: 2, hours_per_day: 24 },
      { id: "4", name: "معدات طبية (Medical Equipment)", power_watts: 1000, quantity: 2, hours_per_day: 6 },
      { id: "5", name: "كمبيوتر (Computers)", power_watts: 200, quantity: 5, hours_per_day: 12 },
    ],
  },
  {
    id: "hospital",
    name: "مستشفى",
    description: "Hospital",
    devices: [
      { id: "1", name: "تكييف مركزي (Central AC)", power_watts: 50000, quantity: 1, hours_per_day: 24 },
      { id: "2", name: "إضاءة (Lighting)", power_watts: 40, quantity: 200, hours_per_day: 24 },
      { id: "3", name: "معدات طبية (Medical Equipment)", power_watts: 2000, quantity: 10, hours_per_day: 12 },
      { id: "4", name: "ثلاجات (Refrigerators)", power_watts: 500, quantity: 10, hours_per_day: 24 },
      { id: "5", name: "كمبيوترات (Computers)", power_watts: 200, quantity: 30, hours_per_day: 24 },
    ],
  },
  {
    id: "bakery",
    name: "مخبز",
    description: "Bakery",
    devices: [
      { id: "1", name: "عجانة (Dough Mixer)", power_watts: 3000, quantity: 2, hours_per_day: 6 },
      { id: "2", name: "فرن كهربائي (Electric Oven)", power_watts: 8000, quantity: 1, hours_per_day: 8 },
      { id: "3", name: "إضاءة (Lighting)", power_watts: 40, quantity: 10, hours_per_day: 12 },
      { id: "4", name: "ثلاجة عرض (Display Fridge)", power_watts: 600, quantity: 1, hours_per_day: 24 },
    ],
  },
  {
    id: "shop",
    name: "دكان",
    description: "Small Shop",
    devices: [
      { id: "1", name: "إضاءة (Lighting)", power_watts: 30, quantity: 6, hours_per_day: 12 },
      { id: "2", name: "ثلاجة (Refrigerator)", power_watts: 400, quantity: 2, hours_per_day: 24 },
      { id: "3", name: "مروحة (Fan)", power_watts: 80, quantity: 2, hours_per_day: 12 },
    ],
  },
  {
    id: "workshop",
    name: "ورشة",
    description: "Workshop",
    devices: [
      { id: "1", name: "ماكينة لحام (Welding Machine)", power_watts: 4000, quantity: 1, hours_per_day: 4 },
      { id: "2", name: "صاروخ تقطيع (Grinder)", power_watts: 1500, quantity: 2, hours_per_day: 3 },
      { id: "3", name: "كمبروسر هواء (Air Compressor)", power_watts: 2500, quantity: 1, hours_per_day: 5 },
      { id: "4", name: "إضاءة (Lighting)", power_watts: 50, quantity: 8, hours_per_day: 10 },
    ],
  },
  {
    id: "water_pump",
    name: "مضخة موية",
    description: "Water Pump Station",
    devices: [
      { id: "1", name: "مضخة رئيسية (Main Pump)", power_watts: 5500, quantity: 1, hours_per_day: 10 },
      { id: "2", name: "إضاءة (Lighting)", power_watts: 30, quantity: 2, hours_per_day: 12 },
    ],
  },
  {
    id: "donkey",
    name: "دونكي",
    description: "Donkey (Water distribution point)",
    devices: [
      { id: "1", name: "مضخة سحب (Suction Pump)", power_watts: 1500, quantity: 1, hours_per_day: 6 },
      { id: "2", name: "إضاءة (Lighting)", power_watts: 20, quantity: 3, hours_per_day: 12 },
    ],
  },
  {
    id: "mosque",
    name: "مسجد",
    description: "Mosque",
    devices: [
      { id: "1", name: "مكيف هواء (Air Conditioner)", power_watts: 1500, quantity: 6, hours_per_day: 4 },
      { id: "2", name: "مراوح (Fans)", power_watts: 80, quantity: 12, hours_per_day: 4 },
      { id: "3", name: "إضاءة (Lighting)", power_watts: 30, quantity: 40, hours_per_day: 5 },
      { id: "4", name: "مكبر صوت (Sound System)", power_watts: 200, quantity: 1, hours_per_day: 2 },
    ],
  },
  {
    id: "printing_press",
    name: "مطبعة",
    description: "Printing Press",
    devices: [
      { id: "1", name: "آلة طباعة (Printing Machine)", power_watts: 5000, quantity: 2, hours_per_day: 8 },
      { id: "2", name: "آلة قص (Cutting Machine)", power_watts: 1500, quantity: 1, hours_per_day: 4 },
      { id: "3", name: "مكيفات (Air Conditioners)", power_watts: 1500, quantity: 2, hours_per_day: 8 },
      { id: "4", name: "إضاءة (Lighting)", power_watts: 40, quantity: 15, hours_per_day: 10 },
    ],
  },
  {
    id: "coffee_shop",
    name: "كوفي شوب",
    description: "Coffee Shop",
    devices: [
      { id: "1", name: "ماكينة اسبريسو (Espresso Machine)", power_watts: 3500, quantity: 1, hours_per_day: 12 },
      { id: "2", name: "مطحنة قهوة (Coffee Grinder)", power_watts: 400, quantity: 2, hours_per_day: 4 },
      { id: "3", name: "ثلاجة عرض (Display Fridge)", power_watts: 500, quantity: 2, hours_per_day: 24 },
      { id: "4", name: "مكيفات (Air Conditioners)", power_watts: 1500, quantity: 2, hours_per_day: 14 },
      { id: "5", name: "إضاءة وديكور (Lighting/Decor)", power_watts: 50, quantity: 20, hours_per_day: 14 },
    ],
  },
  {
    id: "restaurant",
    name: "مطعم",
    description: "Restaurant",
    devices: [
      { id: "1", name: "ثلاجات/فريزرات (Fridges/Freezers)", power_watts: 600, quantity: 4, hours_per_day: 24 },
      { id: "2", name: "مكيفات (Air Conditioners)", power_watts: 1500, quantity: 4, hours_per_day: 14 },
      { id: "3", name: "إضاءة (Lighting)", power_watts: 40, quantity: 30, hours_per_day: 14 },
      { id: "4", name: "معدات مطبخ كهربائية (Kitchen Equipment)", power_watts: 3000, quantity: 2, hours_per_day: 8 },
      { id: "5", name: "مراوح شفط (Exhaust Fans)", power_watts: 400, quantity: 2, hours_per_day: 14 },
    ],
  },
  {
    id: "hotel",
    name: "فندق",
    description: "Hotel",
    devices: [
      { id: "1", name: "مكيفات الغرف (Room ACs)", power_watts: 1200, quantity: 20, hours_per_day: 12 },
      { id: "2", name: "تكييف الاستقبال (Lobby AC)", power_watts: 4000, quantity: 1, hours_per_day: 24 },
      { id: "3", name: "إضاءة (Lighting)", power_watts: 20, quantity: 100, hours_per_day: 12 },
      { id: "4", name: "مصعد (Elevator)", power_watts: 7500, quantity: 1, hours_per_day: 4 },
      { id: "5", name: "سخانات مياه (Water Heaters)", power_watts: 1500, quantity: 10, hours_per_day: 4 },
    ],
  },
  {
    id: "bank",
    name: "بنك",
    description: "Bank",
    devices: [
      { id: "1", name: "تكييف مركزي (Central AC)", power_watts: 10000, quantity: 1, hours_per_day: 10 },
      { id: "2", name: "كمبيوترات (Computers)", power_watts: 200, quantity: 15, hours_per_day: 10 },
      { id: "3", name: "سيرفرات (Servers)", power_watts: 1000, quantity: 2, hours_per_day: 24 },
      { id: "4", name: "إضاءة (Lighting)", power_watts: 40, quantity: 40, hours_per_day: 10 },
      { id: "5", name: "ماكينات صراف آلي (ATMs)", power_watts: 500, quantity: 2, hours_per_day: 24 },
    ],
  },
  {
    id: "supermarket",
    name: "سوبر ماركت",
    description: "Supermarket",
    devices: [
      { id: "1", name: "ثلاجات عرض (Display Fridges)", power_watts: 800, quantity: 5, hours_per_day: 24 },
      { id: "2", name: "فريزرات (Freezers)", power_watts: 1000, quantity: 3, hours_per_day: 24 },
      { id: "3", name: "مكيفات (Air Conditioners)", power_watts: 1500, quantity: 3, hours_per_day: 16 },
      { id: "4", name: "إضاءة (Lighting)", power_watts: 40, quantity: 50, hours_per_day: 16 },
      { id: "5", name: "كاشير (POS Systems)", power_watts: 150, quantity: 3, hours_per_day: 16 },
    ],
  },
  {
    id: "gas_station",
    name: "طرمبة وقود",
    description: "Gas Station",
    devices: [
      { id: "1", name: "مضخات وقود (Fuel Dispensers)", power_watts: 1000, quantity: 4, hours_per_day: 8 },
      { id: "2", name: "إضاءة المظلة (Canopy Lighting)", power_watts: 100, quantity: 10, hours_per_day: 12 },
      { id: "3", name: "إضاءة المحل (Shop Lighting)", power_watts: 40, quantity: 10, hours_per_day: 24 },
      { id: "4", name: "ثلاجة (Refrigerator)", power_watts: 400, quantity: 1, hours_per_day: 24 },
      { id: "5", name: "مكيف (Air Conditioner)", power_watts: 1500, quantity: 1, hours_per_day: 24 },
    ],
  },
  {
    id: "mining_company",
    name: "شركة تعدين",
    description: "Mining Company",
    devices: [
      { id: "1", name: "معدات حفر وتكسير (Drilling/Crushing)", power_watts: 15000, quantity: 2, hours_per_day: 10 },
      { id: "2", name: "مضخات مياه (Water Pumps)", power_watts: 5000, quantity: 2, hours_per_day: 8 },
      { id: "3", name: "إضاءة كاشفة (Floodlights)", power_watts: 400, quantity: 10, hours_per_day: 12 },
      { id: "4", name: "مكيفات المكاتب (Office ACs)", power_watts: 1500, quantity: 4, hours_per_day: 12 },
      { id: "5", name: "كمبيوترات واتصالات (IT/Comms)", power_watts: 1000, quantity: 1, hours_per_day: 24 },
    ],
  },
];
