export const FACILITY_TYPES = [
  { id: 'ice_factory', name: 'مصنع ثلج' },
  { id: 'company', name: 'شركة' },
  { id: 'farm', name: 'مزرعة' },
  { id: 'poultry_farm', name: 'مزرعة دواجن' },
  { id: 'greenhouse', name: 'بيوت محمية' },
  { id: 'factory', name: 'مصنع' },
  { id: 'clinic', name: 'مستوصف' },
  { id: 'hospital', name: 'مستشفي' },
  { id: 'bakery', name: 'مخبز' },
  { id: 'shop', name: 'دكان' },
  { id: 'workshop', name: 'ورشة' },
  { id: 'water_pump', name: 'مضخة مياه' },
  { id: 'water_station', name: 'دونكي' },
  { id: 'mosque', name: 'مسجد' },
  { id: 'printing_press', name: 'مطبعة' },
  { id: 'coffee_shop', name: 'كوفي شوب' },
  { id: 'restaurant', name: 'مطعم' },
  { id: 'hotel', name: 'فندق' },
  { id: 'bank', name: 'بنك' },
  { id: 'supermarket', name: 'سوبر ماركت' },
  { id: 'gas_station', name: 'طرمبة وقود' },
  { id: 'mining_company', name: 'شركة تعدين' }
];

export const APPLIANCES = {
  light: { id: 'light', name: 'لمبة (إضاءة)', typicalWattage: 15 },
  fan: { id: 'fan', name: 'مروحة', typicalWattage: 60 },
  ac_split: { id: 'ac_split', name: 'مكيف سبليت', typicalWattage: 1500 },
  ac_window: { id: 'ac_window', name: 'مكيف شباك', typicalWattage: 1200 },
  fridge: { id: 'fridge', name: 'ثلاجة', typicalWattage: 200 },
  freezer: { id: 'freezer', name: 'فريزر', typicalWattage: 300 },
  tv: { id: 'tv', name: 'تلفزيون', typicalWattage: 100 },
  computer: { id: 'computer', name: 'كمبيوتر', typicalWattage: 250 },
  printer: { id: 'printer', name: 'طابعة', typicalWattage: 50 },
  water_pump_small: { id: 'water_pump_small', name: 'مضخة مياه صغيرة', typicalWattage: 750 },
  water_pump_large: { id: 'water_pump_large', name: 'مضخة مياه كبيرة', typicalWattage: 2200 },
  ice_machine: { id: 'ice_machine', name: 'ماكينة ثلج', typicalWattage: 3000 },
  coffee_machine: { id: 'coffee_machine', name: 'ماكينة قهوة', typicalWattage: 1000 },
  oven: { id: 'oven', name: 'فرن كهربائي', typicalWattage: 2000 },
  blender: { id: 'blender', name: 'خلاط', typicalWattage: 400 },
  speaker: { id: 'speaker', name: 'مكبر صوت', typicalWattage: 50 },
  medical_equipment: { id: 'medical_equipment', name: 'معدات طبية', typicalWattage: 1000 },
  heavy_machinery: { id: 'heavy_machinery', name: 'آلات ثقيلة', typicalWattage: 5000 },
  mining_equipment: { id: 'mining_equipment', name: 'معدات تعدين', typicalWattage: 10000 },
  gas_pump: { id: 'gas_pump', name: 'مضخة وقود', typicalWattage: 1500 },
};

export const FACILITY_DEFAULT_APPLIANCES = {
  ice_factory: [{ applianceId: 'ice_machine', quantity: 2 }, { applianceId: 'light', quantity: 10 }],
  company: [{ applianceId: 'computer', quantity: 10 }, { applianceId: 'ac_split', quantity: 4 }, { applianceId: 'light', quantity: 20 }, { applianceId: 'printer', quantity: 2 }],
  farm: [{ applianceId: 'water_pump_large', quantity: 2 }, { applianceId: 'light', quantity: 10 }],
  poultry_farm: [{ applianceId: 'fan', quantity: 20 }, { applianceId: 'light', quantity: 30 }, { applianceId: 'water_pump_small', quantity: 1 }],
  greenhouse: [{ applianceId: 'fan', quantity: 10 }, { applianceId: 'water_pump_small', quantity: 1 }, { applianceId: 'light', quantity: 5 }],
  factory: [{ applianceId: 'heavy_machinery', quantity: 3 }, { applianceId: 'light', quantity: 50 }, { applianceId: 'ac_split', quantity: 2 }],
  clinic: [{ applianceId: 'medical_equipment', quantity: 2 }, { applianceId: 'fridge', quantity: 1 }, { applianceId: 'ac_split', quantity: 3 }, { applianceId: 'light', quantity: 15 }],
  hospital: [{ applianceId: 'medical_equipment', quantity: 10 }, { applianceId: 'ac_split', quantity: 20 }, { applianceId: 'fridge', quantity: 5 }, { applianceId: 'light', quantity: 100 }],
  bakery: [{ applianceId: 'oven', quantity: 2 }, { applianceId: 'blender', quantity: 1 }, { applianceId: 'light', quantity: 10 }, { applianceId: 'fan', quantity: 4 }],
  shop: [{ applianceId: 'fridge', quantity: 2 }, { applianceId: 'light', quantity: 4 }, { applianceId: 'fan', quantity: 1 }],
  workshop: [{ applianceId: 'heavy_machinery', quantity: 1 }, { applianceId: 'light', quantity: 10 }, { applianceId: 'fan', quantity: 4 }],
  water_pump: [{ applianceId: 'water_pump_large', quantity: 1 }],
  water_station: [{ applianceId: 'water_pump_large', quantity: 2 }, { applianceId: 'light', quantity: 2 }],
  mosque: [{ applianceId: 'ac_split', quantity: 4 }, { applianceId: 'fan', quantity: 10 }, { applianceId: 'light', quantity: 20 }, { applianceId: 'speaker', quantity: 2 }],
  printing_press: [{ applianceId: 'printer', quantity: 5 }, { applianceId: 'computer', quantity: 3 }, { applianceId: 'light', quantity: 15 }, { applianceId: 'ac_split', quantity: 2 }],
  coffee_shop: [{ applianceId: 'coffee_machine', quantity: 2 }, { applianceId: 'fridge', quantity: 1 }, { applianceId: 'ac_split', quantity: 2 }, { applianceId: 'light', quantity: 15 }],
  restaurant: [{ applianceId: 'fridge', quantity: 2 }, { applianceId: 'freezer', quantity: 2 }, { applianceId: 'oven', quantity: 1 }, { applianceId: 'ac_split', quantity: 4 }, { applianceId: 'light', quantity: 20 }],
  hotel: [{ applianceId: 'ac_split', quantity: 20 }, { applianceId: 'tv', quantity: 20 }, { applianceId: 'fridge', quantity: 10 }, { applianceId: 'light', quantity: 100 }],
  bank: [{ applianceId: 'computer', quantity: 15 }, { applianceId: 'ac_split', quantity: 6 }, { applianceId: 'light', quantity: 40 }, { applianceId: 'printer', quantity: 4 }],
  supermarket: [{ applianceId: 'fridge', quantity: 5 }, { applianceId: 'freezer', quantity: 5 }, { applianceId: 'ac_split', quantity: 4 }, { applianceId: 'light', quantity: 30 }],
  gas_station: [{ applianceId: 'gas_pump', quantity: 4 }, { applianceId: 'light', quantity: 20 }, { applianceId: 'fridge', quantity: 1 }],
  mining_company: [{ applianceId: 'mining_equipment', quantity: 5 }, { applianceId: 'heavy_machinery', quantity: 2 }, { applianceId: 'light', quantity: 50 }],
};
