export const facilityTypes = [
  { id: 'ice_factory', name: 'مصنع تلج' },
  { id: 'company', name: 'شركة' },
  { id: 'farm', name: 'مزرعة' },
  { id: 'poultry_farm', name: 'مزرعة دواجن' },
  { id: 'greenhouse', name: 'بيوت محمية' },
  { id: 'factory', name: 'مصنع' },
  { id: 'clinic', name: 'مستوصف' },
  { id: 'hospital', name: 'مستشفى' },
  { id: 'bakery', name: 'مخبز' },
  { id: 'shop', name: 'دكان' },
  { id: 'workshop', name: 'ورشة' },
  { id: 'water_pump', name: 'مضخة موية' },
  { id: 'donkey_pump', name: 'دونكي' },
  { id: 'mosque', name: 'مسجد' },
  { id: 'printing_press', name: 'مطبعة' },
  { id: 'coffee_shop', name: 'كوفي شوب' },
  { id: 'restaurant', name: 'مطعم' },
  { id: 'hotel', name: 'فندق' },
  { id: 'bank', name: 'بنك' },
  { id: 'supermarket', name: 'سوبر ماركت' },
  { id: 'gas_station', name: 'طرمبة وقود' },
  { id: 'mining_company', name: 'شركة تعدين' },
  { id: 'other', name: 'أخرى' },
];

export const commonDevices = [
  { id: 'light', name: 'لمبة (إضاءة)', defaultPower: 15 },
  { id: 'fan', name: 'مروحة سقف', defaultPower: 75 },
  { id: 'ac_split_12', name: 'مكيف اسبليت 12 ألف وحدة', defaultPower: 1200 },
  { id: 'ac_split_18', name: 'مكيف اسبليت 18 ألف وحدة', defaultPower: 1800 },
  { id: 'ac_split_24', name: 'مكيف اسبليت 24 ألف وحدة', defaultPower: 2400 },
  { id: 'fridge', name: 'ثلاجة', defaultPower: 200 },
  { id: 'deep_freezer', name: 'ديب فريزر', defaultPower: 250 },
  { id: 'tv', name: 'تلفزيون', defaultPower: 100 },
  { id: 'computer', name: 'كمبيوتر', defaultPower: 250 },
  { id: 'water_pump_05', name: 'موتور ماء نصف حصان', defaultPower: 375 },
  { id: 'water_pump_10', name: 'موتور ماء واحد حصان', defaultPower: 750 },
];
